# Generated by Django 5.2.4 on 2025-07-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careconnect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentdetails',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
